eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost
jwt:
  secret: dotdev
#3 minutes validity
  token:
    validity: 1800000
springdoc: 
  swagger-ui:
    path:/swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
